version: 2.1
orbs:
  hokusai: artsy/hokusai@volatile
  codecov: codecov/codecov@5.4.3
  horizon: artsy/release@volatile
not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release
only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main
only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release
workflows:
  build-deploy:
    jobs:
      - hokusai/test:
          <<: *not_staging_or_release
          post-steps:
            - run: mkdir -p ./coverage ./reports
            - run:
                name: Copy coverage artifacts
                command: docker cp hokusai_volley_1:/app/coverage ./
                when: always
            - codecov/upload:
                file: ./coverage/lcov.info
            - run:
                name: Copy coverage reports
                command: docker cp hokusai_volley_1:/app/reports ./
                when: always
            - store_test_results:
                path: ./reports
      - hokusai/push:
          name: push-staging-image
          <<: *only_main
          requires:
            - hokusai/test
      - hokusai/deploy-staging:
          <<: *only_main
          project-name: 'volley'
          requires:
            - push-staging-image
      - hokusai/deploy-production:
          <<: *only_release
          requires:
            - horizon/block
      - horizon/block:
          <<: *only_release
          context: horizon
          project_id: 32
