apiVersion: apps/v1
kind: Deployment
metadata:
  name: volley-web
  labels:
    app: volley
    component: web
    layer: application
    app.kubernetes.io/version: production
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: volley
      component: web
      layer: application
  template:
    metadata:
      labels:
        app: volley
        component: web
        layer: application
        app.kubernetes.io/version: production
      name: volley-web
      namespace: default
    spec:
      containers:
      - name: volley-web
        env:
        - name: PORT
          value: '8080'
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: STATSD_PORT
          value: '8125'
        - name: DATADOG_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        envFrom:
        - configMapRef:
            name: volley-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/volley:production
        imagePullPolicy: Always
        ports:
        - name: volley-http
          containerPort: 8080
        readinessProbe:
          httpGet:
            port: volley-http
            path: /health
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: volley-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: volley-web
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: volley
    component: web
    layer: application
  name: volley-web-internal
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    app: volley
    layer: application
    component: web
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volley
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "3m"
spec:
  ingressClassName: nginx
  rules:
  - host: volley.artsy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: volley-web-internal
            port:
              name: http
